[project]
authors = [
  { name = "Sebastijan Zindl", email = "sebastijanzindl@protonmail.com" },
  { name = "Petar Pejoski", email = "petar.pejoski32@gmail.com" },
]
name = "rag-over-finetune"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=1.2.7",
    "langchain-community>=0.4.1",
    "langchain-text-splitters>=1.1.0",
    "python-dotenv>=1.2.1",
    "tiktoken>=0.12.0",
    "sentence-transformers>=5.2.2",
    "langchain-huggingface>=1.2.0",
    "langchain-openai>=1.1.7",
    "langchain-anthropic>=1.3.1",
    "langchain-google-genai>=4.2.0",
    "langchain-ollama>=1.0.1",
    "vezilka-schemas>=0.1.5",
    "openrouter>=0.6.0",
    "qdrant-client",
    "langchain-qdrant",
]

[project.optional-dependencies]
test = [
  "pytest",
  "pytest-cov"
]

[tool.pytest.ini_options]
addopts = "--cov --cov-report html"
strict = true
