from .app import APP_NAME, APP_VERSION
from .defaults import (
    DEFAULT_CHROMA_COLLECTION_NAME,
    DEFAULT_CHROMA_PERSIST_DIR,
    DEFAULT_CONFIG_PATH,
    DEFAULT_DATA_PATH,
    DEFAULT_ENV_PATH,
    DEFAULT_OLLAMA_URL,
    DEFAULT_TEST_QUERIES,
    SAMPLE_DOCUMENTS_PATH,
)

__all__ = [
    "DEFAULT_CHROMA_COLLECTION_NAME",
    "DEFAULT_CHROMA_PERSIST_DIR",
    "DEFAULT_CONFIG_PATH",
    "DEFAULT_DATA_PATH",
    "DEFAULT_ENV_PATH",
    "DEFAULT_OLLAMA_URL",
    "DEFAULT_TEST_QUERIES",
    "SAMPLE_DOCUMENTS_PATH",
    "APP_NAME",
    "APP_VERSION",
]
