DEFAULT_CONFIG_PATH = "./config.json"
DEFAULT_DATA_PATH = "./data"
DEFAULT_ENV_PATH = ".env"
SAMPLE_DOCUMENTS_PATH = "./sample_data/sample_documents.json"

DEFAULT_CHROMA_PERSIST_DIR = "./chroma_db"
DEFAULT_CHROMA_COLLECTION_NAME = "vector_collection"
DEFAULT_QDRANT_URL = "http://localhost:6333"
DEFAULT_QDRANT_COLLECTION_NAME = "mk_rag_collection"
DEFAULT_OLLAMA_URL = "http://localhost:11434"

DEFAULT_ENABLED_QUERY_TRANSFORMS = ["multi_query"]
DEFAULT_MAX_GENERATED_QUERIES = 2
DEFAULT_TRANSFORM_GATE_ENABLED = True

DEFAULT_RETRIEVAL_K_PER_QUERY = 3
DEFAULT_RETRIEVAL_K_TOTAL_BEFORE_RERANK = 10
DEFAULT_RETRIEVAL_MERGE_STRATEGY = "rrf"

DEFAULT_HYDE_INCLUDE_ORIGINAL_QUERY = True
DEFAULT_QUERY_TRANSFORM_TIMEOUT_MS = 2000

DEFAULT_RERANKER_ENABLED = False
DEFAULT_RERANKER_MODEL = "cross-encoder/ms-marco-MiniLM-L-12-v2"
DEFAULT_RERANKER_TOP_N = 5

DEFAULT_INGESTION_BATCH_SIZE = 500

DEFAULT_USE_HIERARCHICAL_INDEXING = False
DEFAULT_PARENT_CHUNK_SIZE = 1500
DEFAULT_PARENT_CHUNK_OVERLAP = 0
DEFAULT_CHILD_CHUNK_SIZE = 300
DEFAULT_CHILD_CHUNK_OVERLAP = 30
DEFAULT_QDRANT_PARENT_COLLECTION_NAME: str | None = None

DEFAULT_TEST_QUERIES = [
    "Кој е главниот град на Македонија?",
    "Колку е длабоко Охридското Езеро?",
    "Што е тавче гравче?",
    "Кој ја создал кирилицата?",
    "Кога е роден Александар Македонски?",
]
